### PR TITLE
Add margarita, fix nobody's fault

### PR DESCRIPTION
**Pull request by stevepescatore**
reviewers @mike-yesware sorry for the premature merge last time. I promise to behave this time. also, I owe you a drink now.

### CODE REVIEW

**Comment by mike-yesware** [comment]
Updating unrelated areas of concern in the same PR is bad form.

G2G

**Comment by ancharon** [comment]
Tests?

**Comment by mkostick** [comment]
`s/recipies/recipes`

Yeah, I'm gonna be that guy :)  Not that I'm against pie or anything.

**Comment by stevepescatore** [comment]
Manual tests only for this repo. I think finding qualified testers should be easy.

**Comment by ancharon** [comment]
:+1:

**Pull request merged**
